services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4007:4007"
    env_file:
      - .env
    volumes:
      - ./server:/app:cached
      - /app/node_modules   # prevent node_modules overwrite
    environment:
      - NODE_ENV=development
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4004:80"
    depends_on:
      - backend
